[package]
name = "clams"
version = "0.0.2"
authors = ["Lukas Pustina <lukas@pustina.net>"]
description = "Clams help bulding shells"
readme = "README.md"
license = "MIT"
keywords = ["shell", "cli"]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]

[badges]
travis-ci = { repository = "lukaspustina/clams", branch = "master" }
codecov = { repository = "lukaspustina/clams", branch = "master", service = "github" }

[dependencies]
colored = "^1.6"
error-chain = "^0.11"
log = "^0.4"
fern = { version = "^0.5", features = ["colored"] }
subprocess = "^0.1"

[dev-dependencies]
spectral = "^0.6"

