[package]
name = "clam"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]

[[bin]]
name = "mv_videos"
path = "src/bin/mv_videos.rs"

[dependencies]
failure = "^0.1"
failure_derive = "^0.1"
log = "^0.4"
loggerv = "^0.7"
structopt = "^0.2"
subprocess = "^0.1"

[dev-dependencies]
spectral = "^0.6"